name: SmitePlugin
main: Hax.Bukkit.SmitePlugin.SmitePlugin
version: 1.0

commands:
   smite:
      description: This command absolutely obliterates players, entities, and specified locations.
      usage: /smite [x] [y] [z] OR /smite playerName OR /smite @p, @a, @r, or @e
      permission: SmitePlugin.smite
      permission-message: You don't have the permissions, friend.